Фикс билдера 7 (#9193)
* Фикс билдера

* Update build_rust.yml

* Фикс билдера 4

* Фикс билдера 5

* Фикс билдера 6

* Фикс билдера 7

diff --git a/.github/workflows/build_rust.yml b/.github/workflows/build_rust.yml
--- a/.github/workflows/build_rust.yml
+++ b/.github/workflows/build_rust.yml
@@ -129,10 +129,10 @@ jobs:
       - run: echo "FAIL_NOTIFIED=false" >> "$env:GITHUB_ENV"
 
       - name: Like the comment
+        shell: bash
         env:
           BASE_REPOSITORY: ${{ github.repository }}
           GH_TOKEN: ${{ github.token }}
-        shell: bash
         run: |
           gh api \
             --method POST \
@@ -163,21 +163,23 @@ jobs:
         uses: msys2/setup-msys2@v2
         with:
           msystem: MINGW32
-          install: mingw-w64-i686-gcc mingw-w64-i686-make
-
-      - name: Setup Rust
-        shell: msys2 {0}
-        run: |
-          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-          source ~/.cargo/env
-          rustup target add i686-pc-windows-gnu
+          install: mingw-w64-i686-gcc
 
       - name: Build Windows DLL
         shell: msys2 {0}
         run: |
-          source ~/.cargo/env
+          export PATH="/c/Users/runneradmin/.cargo/bin:$PATH"
+
+          which cargo || echo "Cargo not found, installing..."
+
+          if ! command -v cargo &> /dev/null; then
+            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-host x86_64-pc-windows-gnu
+            export PATH="$HOME/.cargo/bin:$PATH"
+          fi
+
+          rustup target add i686-pc-windows-gnu
+
           cd rust
-          export PATH=/mingw32/bin:$PATH
           cargo build --release --target i686-pc-windows-gnu
           cp target/i686-pc-windows-gnu/release/rustlibs.dll ../rustlibs.dll
 
